In [2]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created using passed list:\n",a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [3]:
b=np.zeros((3,4))
print("\n An array initialized with all zeros.\n",b)


 An array initialized with all zeros.
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
c=np.full((3,3),6)
print("\n array initialized with all 6.\n",c)


 array initialized with all 6.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [5]:
d=np.random.random((2,2))
print("\n a random array.\n",d)


 a random array.
 [[0.59663686 0.84609095]
 [0.3656133  0.85981049]]


In [7]:
e=np.arange(0,35,5)
print("\n a sequential array with step pf 5.\n",e)


 a sequential array with step pf 5.
 [ 0  5 10 15 20 25 30]


In [8]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
reshaped_arr=arr.reshape(4,3)
print(arr)
print(reshaped_arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [9]:
fl_arr=arr.flatten()
print(arr)
print(fl_arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[1 2 3 4 5 2 4 2 1 2 0 1]


In [10]:
print(arr.ndim)

2


In [11]:
print(arr.shape)

(3, 4)


In [12]:
print(arr.size)

12


In [13]:
print(arr.dtype)

int32


In [14]:
c=arr.astype('f')
print(c)
b=arr.astype('i')
print(b)

[[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]


In [15]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:3])

[]


In [16]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('i')
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [17]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2:,2:])


[[ 9]
 [12]
 [15]]
